import type {
  Guild,
  GuildMembership,
  GuildQuest,
  RoleSignal,
  TreasuryEntry,
  WorkRecord,
} from './domain.js';

/**
 * How the guild feature stores what it knows, without naming a database.
 *
 * Same reasoning as every other feature's repository: the feature may not import
 * drizzle or anything else in `infrastructure`, so it states what it needs and
 * the wiring supplies it. The store cannot import this file either, so the two
 * sides agree on plain shapes rather than on classes.
 *
 * ── Why three of these are "record once" and answer with a boolean ──────────
 *
 * A GitHub merge is delivered at least once and promises no order, and the
 * whole guild ledger is built on "an outcome is counted once". A port whose
 * write returns nothing cannot express that, so the caller has to read first
 * and then write, and the gap between those two statements is a window in which
 * a retried delivery counts twice. `recordWork` and `recordRoleSignal` return
 * whether THIS call is the one that recorded the row; `false` means somebody
 * already had, which is an ordinary answer and not a failure.
 *
 * `join` is the same shape for the same reason: two requests for the same
 * membership arriving together must produce one row, and "the first one wins"
 * is the same answer whichever request lost.
 */
export interface GuildRepository {
  /* ── guilds ── */

  create(guild: NewGuild, now: string): Promise<Guild>;
  find(guildId: string): Promise<Guild | undefined>;
  /** Every guild, oldest first, so a board has a total order to sort within. */
  list(): Promise<readonly Guild[]>;

  /* ── membership ── */

  /** The membership, and whether this call created it. */
  join(
    guildId: string,
    agentId: string,
    now: string,
  ): Promise<{ readonly row: GuildMembership; readonly created: boolean }>;
  /** Whether a membership was there to remove. */
  leave(guildId: string, agentId: string): Promise<boolean>;
  isMember(guildId: string, agentId: string): Promise<boolean>;
  /** Every guild an agent belongs to. The ACL's hot path on the sending side. */
  guildsOf(agentId: string): Promise<readonly string[]>;
  members(guildId: string): Promise<readonly GuildMembership[]>;

  /* ── the work ledger ── */

  /** The record, and whether this call wrote it. `false` = already counted. */
  recordWork(
    entry: NewWorkRecord,
  ): Promise<{ readonly row: WorkRecord; readonly created: boolean }>;
  /**
   * A guild's work, newest first.
   *
   * `repository` narrows to one `owner/name`; `from`/`to` bound the window a
   * tally reads. Omitted bounds mean unbounded, because "this guild's whole
   * history" is a question a quest asks and "this week" is a question a tally
   * asks, and neither is derivable from the other.
   */
  workFor(
    guildId: string,
    query?: { readonly repository?: string; readonly from?: string; readonly to?: string },
  ): Promise<readonly WorkRecord[]>;

  /* ── the treasury ── */

  /**
   * Appends a row. `id` is generated by the store, so two callers appending at
   * the same instant cannot collide on an id they both chose.
   */
  appendTreasuryEntry(entry: NewTreasuryEntry): Promise<TreasuryEntry>;
  treasuryFor(guildId: string): Promise<readonly TreasuryEntry[]>;

  /* ── quests ── */

  createQuest(quest: NewQuest): Promise<GuildQuest>;
  quests(guildId: string): Promise<readonly GuildQuest[]>;
  /**
   * Stamps a quest's completion instant, and whether this call is the one that
   * did it.
   *
   * `false` for a quest that was already complete is the answer a second
   * delivery needs, and a `completedAt` that moves every time a counter crosses
   * the goal would be a different fact from the one this column holds: WHEN the
   * goal was first met.
   */
  completeQuest(questId: string, at: string): Promise<boolean>;

  /* ── role evidence ── */

  /** The signal, and whether this call wrote it. `false` = already recorded. */
  recordRoleSignal(
    signal: NewRoleSignal,
  ): Promise<{ readonly row: RoleSignal; readonly created: boolean }>;
  roleSignalsFor(agentId: string): Promise<readonly RoleSignal[]>;
}

export interface NewGuild {
  readonly name: string;
  readonly tag: string;
  readonly foundedByAgentId: string;
}

export interface NewWorkRecord {
  readonly guildId: string;
  readonly agentId: string;
  readonly bountyId: string;
  readonly repository: string;
  readonly sourceType: string;
  readonly occurredAt: string;
}

export interface NewTreasuryEntry {
  readonly guildId: string;
  readonly kind: 'contribution' | 'commitment';
  readonly amountCents: number;
  readonly contributorUserId: string | null;
  readonly bountyId: string | null;
  readonly committedByAgentId: string | null;
  readonly createdAt: string;
}

export interface NewQuest {
  readonly guildId: string;
  readonly title: string;
  readonly repository: string | null;
  readonly goal: number;
  readonly createdAt: string;
}

export interface NewRoleSignal {
  readonly agentId: string;
  readonly role: 'researcher' | 'coder' | 'tester' | 'reviewer';
  readonly weight: number;
  readonly sourceType: string;
  readonly sourceKey: string;
  readonly occurredAt: string;
}
