import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { DatabaseSync } from 'node:sqlite';

/**
 * A real OpenCode database, built rather than committed.
 *
 * The tables and column names are the ones on this machine's OpenCode 1.18.21,
 * read out of `~/.local/share/opencode/opencode.db` with a read-only handle, and
 * both generations are reproduced: `session` / `message` / `part` and
 * `session_v2` / `session_message`. A committed `.db` was the other option and
 * it is the worse one — a binary blob in git that no review can read, whose
 * contents have to be regenerated by hand the first time the schema moves, and
 * which then silently keeps testing a schema OpenCode left behind. A builder is
 * a schema and a list of rows, both of which a diff can read.
 *
 * What is NOT faked is the database: this is SQLite, in WAL mode, written
 * through a second write connection, so the concurrency test below is about
 * SQLite's locking rather than about a stand-in.
 *
 * It lives under `tests/` rather than beside the tests because the root project
 * typechecks every TypeScript file under `tests`, while a package's own tsconfig
 * has a `rootDir` of its own `src` — a helper imported from inside the package
 * would drag a file outside `rootDir` into a `composite` project and break
 * `tsc -b` for the whole build.
 */

/** Epoch ms the fixtures are stamped from, so nothing depends on the wall clock. */
export const FIXTURE_EPOCH_MS = Date.parse('2026-09-26T09:00:00.000Z');

export type OpenCodeGeneration = 'v1' | 'v2';

/** Every table a fixture writes into, across both schema generations. */
export type FixtureTable = 'session' | 'session_v2' | 'message' | 'part' | 'session_message';

export interface SessionFixture {
  readonly id: string;
  readonly directory?: string;
  readonly parentId?: string;
  readonly projectId?: string;
  readonly createdAt?: number;
  readonly updatedAt?: number;
  readonly archivedAt?: number;
}

export interface MessageFixture {
  readonly id: string;
  readonly sessionId: string;
  readonly data: unknown;
  readonly createdAt?: number;
  readonly updatedAt?: number;
}

export interface PartFixture {
  readonly id: string;
  readonly messageId: string;
  readonly sessionId: string;
  readonly data: unknown;
  readonly createdAt?: number;
  readonly updatedAt?: number;
}

export interface OpenCodeFixtureOptions {
  readonly generation?: OpenCodeGeneration;
  readonly sessions?: readonly SessionFixture[];
  /** v1 only. A v2 turn carries its own parts inline in `data.content`. */
  readonly messages?: readonly MessageFixture[];
  readonly parts?: readonly PartFixture[];
}

/**
 * A writable handle onto a fixture database, standing in for OpenCode.
 *
 * Held open for the lifetime of a test so the read-only reader under test is
 * always looking at a database a live writer owns — which is the only state the
 * WAL caution in the plan is about.
 */
export class OpenCodeFixture {
  readonly #db: DatabaseSync;
  #transactionOpen = false;

  constructor(
    readonly directory: string,
    readonly path: string,
    readonly generation: OpenCodeGeneration,
  ) {
    this.#db = new DatabaseSync(path);
    this.#db.exec('PRAGMA journal_mode = WAL');
    this.#createSchema();
  }

  /** Writes a row the way the harness would, outside any explicit transaction. */
  write(table: FixtureTable, columns: Record<string, unknown>): void {
    const names = Object.keys(columns);
    const placeholders = names.map(() => '?').join(', ');
    this.#db
      .prepare(`INSERT OR REPLACE INTO ${table} (${names.join(', ')}) VALUES (${placeholders})`)
      .run(...names.map((name) => normaliseColumn(columns[name])));
  }

  /**
   * Opens a write transaction and leaves it open.
   *
   * A SQLite writer mid-transaction holds the reserved lock on the database,
   * which is the state a reader has to survive: a read-write reader would block
   * here, and a read-only one sees the committed rows and nothing else.
   */
  beginUncommittedWrite(): void {
    this.#db.exec('BEGIN IMMEDIATE');
    this.#transactionOpen = true;
  }

  /** Closes the transaction opened above, committing or rolling back. */
  endUncommittedWrite(commit: boolean): void {
    if (!this.#transactionOpen) return;
    this.#db.exec(commit ? 'COMMIT' : 'ROLLBACK');
    this.#transactionOpen = false;
  }

  /**
   * Raw DDL, for the one scenario a running watcher really has to survive: the
   * harness changing its schema underneath a reader that prepared its statements
   * at start-up. A test can drop the table a poll reads and watch the loop back
   * off rather than die.
   */
  exec(sql: string): void {
    this.#db.exec(sql);
  }

  /** Every file sitting next to the database, so a test can assert on the WAL. */
  sidecars(): readonly string[] {
    return [this.path, `${this.path}-wal`, `${this.path}-shm`, `${this.path}-journal`];
  }

  close(): void {
    this.endUncommittedWrite(false);
    this.#db.close();
  }

  #createSchema(): void {
    if (this.generation === 'v2') {
      this.#db.exec(`
        CREATE TABLE session_v2 (
          id text PRIMARY KEY, project_id text NOT NULL, workspace_id text, parent_id text,
          slug text NOT NULL, directory text NOT NULL, path text, title text, version text NOT NULL,
          agent text, model text, cost real DEFAULT 0 NOT NULL,
          time_created integer NOT NULL, time_updated integer NOT NULL, time_archived integer
        );
        CREATE TABLE session_message (
          id text PRIMARY KEY, session_id text NOT NULL, type text NOT NULL, seq integer NOT NULL,
          time_created integer NOT NULL, time_updated integer NOT NULL, data text NOT NULL
        );
      `);
      return;
    }
    this.#db.exec(`
      CREATE TABLE session (
        id text PRIMARY KEY, project_id text NOT NULL, workspace_id text, parent_id text,
        slug text NOT NULL, directory text NOT NULL, path text, title text NOT NULL, version text NOT NULL,
        agent text, model text, cost real DEFAULT 0 NOT NULL,
        time_created integer NOT NULL, time_updated integer NOT NULL, time_archived integer
      );
      CREATE TABLE message (
        id text PRIMARY KEY, session_id text NOT NULL,
        time_created integer NOT NULL, time_updated integer NOT NULL, data text NOT NULL
      );
      CREATE TABLE part (
        id text PRIMARY KEY, message_id text NOT NULL, session_id text NOT NULL,
        time_created integer NOT NULL, time_updated integer NOT NULL, data text NOT NULL
      );
    `);
  }
}

/** Builds a database in a fresh temp directory and fills it from the fixture. */
export function createOpenCodeFixture(options: OpenCodeFixtureOptions = {}): OpenCodeFixture {
  const generation = options.generation ?? 'v2';
  const directory = mkdtempSync(join(tmpdir(), 'opencode-db-'));
  const fixture = new OpenCodeFixture(directory, join(directory, 'opencode.db'), generation);

  const sessionTable = generation === 'v2' ? 'session_v2' : 'session';
  for (const session of options.sessions ?? []) {
    fixture.write(sessionTable, {
      id: session.id,
      project_id: session.projectId ?? 'project-1',
      parent_id: session.parentId ?? null,
      slug: session.id,
      directory: session.directory ?? '/repo',
      title: 'a session',
      version: '1.18.21',
      agent: 'build',
      model: 'model-1',
      time_created: session.createdAt ?? FIXTURE_EPOCH_MS,
      time_updated: session.updatedAt ?? session.createdAt ?? FIXTURE_EPOCH_MS,
      time_archived: session.archivedAt ?? null,
    });
  }
  // A `message` fixture row becomes a `session_message` row in v2, because that
  // is the same thing in the newer schema: a turn. `type` and `seq` are NOT NULL
  // there, so they are derived from the payload rather than left to the caller.
  (options.messages ?? []).forEach((message, index) => {
    const payload = message.data as Record<string, unknown>;
    fixture.write(generation === 'v2' ? 'session_message' : 'message', {
      id: message.id,
      session_id: message.sessionId,
      ...(generation === 'v2' ? { type: payload.type ?? 'assistant', seq: index } : {}),
      time_created: message.createdAt ?? FIXTURE_EPOCH_MS,
      time_updated: message.updatedAt ?? message.createdAt ?? FIXTURE_EPOCH_MS,
      data: JSON.stringify(message.data),
    });
  });
  if (generation === 'v2' && (options.parts ?? []).length > 0) {
    throw new Error('a v2 fixture has no part rows: a turn carries its parts inside data.content');
  }
  for (const part of options.parts ?? []) {
    fixture.write('part', {
      id: part.id,
      message_id: part.messageId,
      session_id: part.sessionId,
      time_created: part.createdAt ?? FIXTURE_EPOCH_MS,
      time_updated: part.updatedAt ?? part.createdAt ?? FIXTURE_EPOCH_MS,
      data: JSON.stringify(part.data),
    });
  }
  return fixture;
}

/** Removes a fixture and its directory. A test that forgets this leaks a WAL. */
export function removeOpenCodeFixture(fixture: OpenCodeFixture): void {
  fixture.close();
  rmSync(fixture.directory, { recursive: true, force: true });
}

// ── row shapes, copied from the databases on this machine ──────────────────

/** A v2 assistant turn with a tool call in it. */
export function assistantTurn(options: {
  readonly tools?: readonly ToolCallFixture[];
  readonly reasoning?: boolean;
  readonly answer?: string;
  readonly error?: string;
  readonly createdAt?: number;
  readonly completedAt?: number;
}): Record<string, unknown> {
  const content: Record<string, unknown>[] = [];
  if (options.reasoning === true) {
    content.push({
      type: 'reasoning',
      text: '',
      time: { created: options.createdAt ?? FIXTURE_EPOCH_MS },
    });
  }
  for (const tool of options.tools ?? []) {
    content.push({
      type: 'tool',
      id: tool.callId,
      name: tool.name,
      executed: false,
      state: {
        status: tool.status,
        input: tool.input,
        ...(tool.error === undefined ? {} : { error: tool.error }),
      },
      time: {
        created: tool.createdAt ?? FIXTURE_EPOCH_MS,
        ran: tool.createdAt ?? FIXTURE_EPOCH_MS,
        completed: tool.completedAt ?? (tool.createdAt ?? FIXTURE_EPOCH_MS) + 25,
      },
    });
  }
  if (options.answer !== undefined) content.push({ type: 'text', text: options.answer });
  return {
    agent: 'build',
    model: { id: 'model-1', providerID: 'opencode', variant: 'default' },
    content,
    time: {
      created: options.createdAt ?? FIXTURE_EPOCH_MS,
      completed: options.completedAt ?? FIXTURE_EPOCH_MS,
    },
    ...(options.error === undefined
      ? {}
      : { error: { name: 'ProviderError', message: options.error } }),
  };
}

export interface ToolCallFixture {
  readonly callId: string;
  readonly name: string;
  readonly input?: Record<string, unknown>;
  readonly status?: string;
  readonly error?: string;
  readonly createdAt?: number;
  readonly completedAt?: number;
}

/** A v1 tool part, whose call id lives on `callID` rather than on `id`. */
export function toolPart(call: ToolCallFixture): Record<string, unknown> {
  return {
    type: 'tool',
    callID: call.callId,
    tool: call.name,
    state: {
      status: call.status ?? 'completed',
      input: call.input ?? {},
      ...(call.error === undefined ? {} : { error: call.error }),
    },
  };
}

function normaliseColumn(value: unknown): string | number | null {
  if (value === undefined) return null;
  if (typeof value === 'boolean') return value ? 1 : 0;
  if (typeof value === 'string' || typeof value === 'number') return value;
  return JSON.stringify(value);
}
